### ISSUE TITLE
(Дизайнер) Сделать более приятное меню для новеллы (до 4.12)

### ISSUE THREAD

**Issue by valerijGH** [valerijGH/Novel#15]
В данный момент у нас вот такое меню(дефолтное)
Можно просто подобрать шрифт какой-либо и нарисовать фон

![Image](https://github.com/valerijGH/Novel/assets/97888593/95d8ba6e-e929-47a2-8181-761e08d60ea0)

Главное чтобы смотрелось гармонично 

и скинуть все раздельно

**Comment by NeGeterohromat** [comment]
59 95 34 - цвет разделительной линии
Monotype Corsiva - шрифт
затенение 60%


[menu.zip](https://github.com/valerijGH/Novel/files/13539345/menu.zip)
