### ISSUE TITLE
(Аналитик) Сделать аналитику...

### ISSUE THREAD

**Issue by valerijGH** [valerijGH/Novel#3]
Проанализировать выбранную профессию, и изучить целевую аудиторию новеллы.

**Comment by khovansky007** [comment]
версия 3: https://docs.google.com/document/d/15abKyEFIdhtEcpj_-2x6YMCTxeN9-lSu/edit?usp=sharing&ouid=116716616575655120551&rtpof=true&sd=true

**Comment by khovansky007** [comment]
**Текст к презентации аналитической части**

Мы решили сделать визуальную новелу для старших классов школ.
Для того, чтобы понять, что интересно нашей аудитории,
мы провели опрос среди 11-классников четырех школ на Урале,
также мы организовали глубинное интерьвью с представителем нашей аудитории.
В ходе общения с ним были выдвинуты гипотезы (высокая тревожность в выпускных классах; незнание, зачем им 
высшее образование; высокий уровень заинтересованности в его получении),
которые подвердились в ходе изучения материалов исследований из открытых источников.

После изучения всех опросов и исследований мы выяснили, что наша аудитория - 11-классники 17-18 лет, которые в основном
любят творческое направление (рисование), чем занятие техническими предметами, 
при этом их интересует IT сфера. 
Им интересен романтический и приключенческий контент в стиле аниме. 
Они не особо увлечены книгами, готовы уделить игре лишь 15-30 минут. 
Их волнует вопрос поступления. Многие не знают, 
кем хотят стать. Они испытывают высокую ситуативную и личностную тревожность. Всё на них давит, начиная от банальных подступающих экзаменов,
заканчивая самоопределением в жизни.
Информацию они получают в основном через ютуб и вк. 
Желание работать на высокооплачиваемой должности намного приоритетней, чем иметь интересную работу.

Ищя решение проблемы будущих студентов, мы решили узнать, что же вообще может предложить интернет
потерянным выпускникам. Мы рассмотрели самые популярые виды решений, которые связаны с самоопределением школьников.
Самым популярным из них стал Яндекс Практикум «promo test», из плюсов можно выделить обширность предлагаемых профессий,
интерактивное оформление результатов, что лучше донесет информацию и, соответсвенно, будет профитнее. Из явных минусов можно выделить объемность текста,
наши школьники читают с неохотой. Вторым по полурности является ютуб канал "Глеб Соломин" со средними
просмотрами в размере семисот тысяч, построенный исключительно на самообразовывающем 
контенте, а именно это подкасты с успешными представителями сфер, часто рассматриваются кейсы с абитуриентами и преподавателями популярных вузов страны.
Очевидным плюсом является мультимедийность продукта, в контенте присутвует видео, аудио и изобразительная часть, также плюсом являются конкретные примеры, где ты можешь посмотреть на таких же людей, как и ты.
При таком количестве плюсов есть и недостатки, а именно длина контента, часто разговор становится затянум, повторяется одно и то же.
Еще одним конкурентов стал ресурс Trudvsem.ru, популярный сайт, выдаваемый на уроках профориентации в школах. Из положительного здесь только наглядность вариантов профессий, ты сразу можешь увидеть интерактивные карточки с кратким описанием и необходимыми наваками.
Хоть в школах и проводят уроки проф. ориентации, школьникам это особо не помогает, к примеру, потому что
в этом варианте нет никакой мультимедийности, что очень важно для соверменного поколения, способность концентрироваться и провлять интерес к данному типу контента искренне очень сложно, также минусом являются слишком общие рекомендации.

Из всего этого мы сделали следующий вывод:
Нужно суметь заинтересовать пользователя (в том числе отказаться от большого количества текста, добавить больше интерактивности),
чтобы он не перестал пользоваться нашим продуктом уже через 5 минут. 
Показать конкретную профессию на примере. Добавить разнообразных интересных персонажей, которым выпускники будут сопереживать и понимать их.

Мы поняли, кто наши пользователи, и, что им нужно.
Наш продукт сделан для выпускников 11-го класса с целью помочь определится с профессией,
рассказать об одной из них, снять избыточную тревожность и просто дать возможность
провести время с удовольствием, играя в нашу интересную и полезную визуальную новеллу. 

Команда получила конкретные требования к разработке для эффекстивного решения выпускников,
которые были воплощены в нашей новелле.
{Перечисление реализованных требований...}
''' РЕКОМЕНДАЦИЯ КОМАНДЕ К РАЗРАБОТКЕ НОВЕЛЫ
	профессия должна быть в сфере IT и завязана на дизайне и рисовании
	визуал в стиле аниме
	романтический и приключенческий жанр
	протяженность новеллы 15-30 минут
	упомянуть высокую заработную плату
	дать понять, что нужно поступать в ВУЗ (общее развитие, полезная социальная среда...)
	новелла должна помочь:
o	выбрать направление обучения
o	с профессиональным самоопределением
o	с выбором перспективной профессии
o	снять уровень тревожности (тревога из-за ЕГЭ, давления родителей, учителей и непонимания того, что делать в жизни)
	Нужно суметь заинтересовать пользователя (в том числе отказаться от большого количества текста, добавить больше интерактивности)
	Показать конкретную профессии на примере
	Добавить разнообразных интересных персонажей
'''

**Comment by khovansky007** [comment]
версия 4 https://docs.google.com/document/d/1LOWN5E8Xiz1m_jzivYb4VVosZN9TZfH_/edit?usp=sharing&ouid=116716616575655120551&rtpof=true&sd=true

доделаны части для получения 10 балов за аналитику, обновлена таблица со сравнением конкурентов
