### ISSUE TITLE
(Дизайнер) Нарисовать то, как ГГ смотрит на Плакат с Дроа на стене (до 27.11)

### ISSUE THREAD

**Issue by valerijGH** [valerijGH/Novel#7]
Момент, где гг думает о том, что хочет попасть на концерт любимой исполнительницы (пока сидит за компьютером) и бросает взгляд на плакат с Дроа на стене

**Comment by NeGeterohromat** [comment]
[с компа глаза вверх.zip](https://github.com/valerijGH/Novel/files/13464876/default.zip)
