### ISSUE TITLE
(Дизайнер) Дорисовать диалог с Тимохой (до 27.11)

### ISSUE THREAD

**Issue by valerijGH** [valerijGH/Novel#8]
Диалог происходит в телефоне
Трофим представлял это как 
![Image](https://github.com/valerijGH/Novel/assets/97888593/bee90d72-4947-4fd6-9ce8-b9b9137e3d5f)

просто подставить аватарки, оформить это как диалог
а вместо реплик просто волнистые строчки ну или что-то не разборчиво(просто, что бы понимать, что идет диалог)

**Comment by NeGeterohromat** [comment]
[мессенджер.zip](https://github.com/valerijGH/Novel/files/13467156/default.zip)
